export const postcodeMap: Record<string, { city: string; region: string }> = {
  // London
  E:  { city: "East London", region: "London" },
  EC: { city: "Central London", region: "London" },
  N:  { city: "North London", region: "London" },
  NW: { city: "North West London", region: "London" },
  SE: { city: "South East London", region: "London" },
  SW: { city: "South West London", region: "London" },
  W:  { city: "West London", region: "London" },
  WC: { city: "Central London", region: "London" },
  BR: { city: "Bromley", region: "London" },
  CR: { city: "Croydon", region: "London" },
  DA: { city: "Dartford", region: "London" },
  EN: { city: "Enfield", region: "London" },
  HA: { city: "Harrow", region: "London" },
  IG: { city: "Ilford", region: "London" },
  KT: { city: "Kingston upon Thames", region: "London" },
  RM: { city: "Romford", region: "London" },
  SM: { city: "Sutton", region: "London" },
  TW: { city: "Twickenham", region: "London" },
  UB: { city: "Uxbridge", region: "London" },
  WD: { city: "Watford", region: "London" },

  // South East
  BN: { city: "Brighton", region: "South East" },
  GU: { city: "Guildford", region: "South East" },
  HP: { city: "High Wycombe", region: "South East" },
  ME: { city: "Medway", region: "South East" },
  OX: { city: "Oxford", region: "South East" },
  PO: { city: "Portsmouth", region: "South East" },
  RG: { city: "Reading", region: "South East" },
  RH: { city: "Redhill", region: "South East" },
  SL: { city: "Slough", region: "South East" },
  SO: { city: "Southampton", region: "South East" },
  TN: { city: "Tonbridge", region: "South East" },

  // South West
  BA: { city: "Bath", region: "South West" },
  BS: { city: "Bristol", region: "South West" },
  DT: { city: "Dorchester", region: "South West" },
  EX: { city: "Exeter", region: "South West" },
  GL: { city: "Gloucester", region: "South West" },
  PL: { city: "Plymouth", region: "South West" },
  SN: { city: "Swindon", region: "South West" },
  SP: { city: "Salisbury", region: "South West" },
  TA: { city: "Taunton", region: "South West" },
  TQ: { city: "Torquay", region: "South West" },
  TR: { city: "Truro", region: "South West" },

  // West Midlands
  B:  { city: "Birmingham", region: "West Midlands" },
  CV: { city: "Coventry", region: "West Midlands" },
  DY: { city: "Dudley", region: "West Midlands" },
  WS: { city: "Walsall", region: "West Midlands" },
  WV: { city: "Wolverhampton", region: "West Midlands" },

  // East Midlands
  DE: { city: "Derby", region: "East Midlands" },
  LE: { city: "Leicester", region: "East Midlands" },
  LN: { city: "Lincoln", region: "East Midlands" },
  NG: { city: "Nottingham", region: "East Midlands" },
  NN: { city: "Northampton", region: "East Midlands" },

  // East of England
  AL: { city: "St Albans", region: "East of England" },
  CB: { city: "Cambridge", region: "East of England" },
  CM: { city: "Chelmsford", region: "East of England" },
  CO: { city: "Colchester", region: "East of England" },
  IP: { city: "Ipswich", region: "East of England" },
  LU: { city: "Luton", region: "East of England" },
  NR: { city: "Norwich", region: "East of England" },
  PE: { city: "Peterborough", region: "East of England" },
  SG: { city: "Stevenage", region: "East of England" },

  // Yorkshire and The Humber
  BD: { city: "Bradford", region: "Yorkshire and The Humber" },
  DN: { city: "Doncaster", region: "Yorkshire and The Humber" },
  HD: { city: "Huddersfield", region: "Yorkshire and The Humber" },
  HG: { city: "Harrogate", region: "Yorkshire and The Humber" },
  HU: { city: "Hull", region: "Yorkshire and The Humber" },
  LS: { city: "Leeds", region: "Yorkshire and The Humber" },
  S:  { city: "Sheffield", region: "Yorkshire and The Humber" },
  WF: { city: "Wakefield", region: "Yorkshire and The Humber" },
  YO: { city: "York", region: "Yorkshire and The Humber" },

  // North West
  BB: { city: "Blackburn", region: "North West" },
  BL: { city: "Bolton", region: "North West" },
  CH: { city: "Chester", region: "North West" },
  FY: { city: "Blackpool", region: "North West" },
  L:  { city: "Liverpool", region: "North West" },
  LA: { city: "Lancaster", region: "North West" },
  M:  { city: "Manchester", region: "North West" },
  OL: { city: "Oldham", region: "North West" },
  PR: { city: "Preston", region: "North West" },
  SK: { city: "Stockport", region: "North West" },
  WA: { city: "Warrington", region: "North West" },
  WN: { city: "Wigan", region: "North West" },

  // North East
  DH: { city: "Durham", region: "North East" },
  DL: { city: "Darlington", region: "North East" },
  NE: { city: "Newcastle upon Tyne", region: "North East" },
  SR: { city: "Sunderland", region: "North East" },
  TS: { city: "Middlesbrough", region: "North East" },

  // Scotland
  AB: { city: "Aberdeen", region: "Scotland" },
  DD: { city: "Dundee", region: "Scotland" },
  DG: { city: "Dumfries", region: "Scotland" },
  EH: { city: "Edinburgh", region: "Scotland" },
  FK: { city: "Falkirk", region: "Scotland" },
  G:  { city: "Glasgow", region: "Scotland" },
  HS: { city: "Outer Hebrides", region: "Scotland" },
  IV: { city: "Inverness", region: "Scotland" },
  KA: { city: "Kilmarnock", region: "Scotland" },
  KW: { city: "Kirkwall", region: "Scotland" },
  KY: { city: "Kirkcaldy", region: "Scotland" },
  ML: { city: "Motherwell", region: "Scotland" },
  PA: { city: "Paisley", region: "Scotland" },
  PH: { city: "Perth", region: "Scotland" },
  TD: { city: "Galashiels", region: "Scotland" },
  ZE: { city: "Lerwick", region: "Scotland" },

  // Wales
  CF: { city: "Cardiff", region: "Wales" },
  LD: { city: "Llandrindod Wells", region: "Wales" },
  LL: { city: "Llandudno", region: "Wales" },
  NP: { city: "Newport", region: "Wales" },
  SA: { city: "Swansea", region: "Wales" },
  SY: { city: "Shrewsbury", region: "Wales" },

  // Northern Ireland
  BT: { city: "Belfast", region: "Northern Ireland" },
};