-- ============================================================================
-- Seed Script: seed_task_templates.sql
-- Description: Inserts default compliance task templates for tenants without data
-- ============================================================================

insert into public.task_templates (
  company_id,
  name,
  slug,
  description,
  category,
  audit_category,
  frequency,
  dayparts,
  assigned_to_role,
  compliance_standard,
  is_critical,
  is_template_library,
  is_active,
  evidence_types,
  instructions
)
values
  (
    null,
    'Daily Opening Food Safety Check',
    'daily_opening_food_safety',
    'Pre-service checks for fridges, freezers and prep areas before service.',
    'food_safety',
    'food_safety',
    'daily',
    array['before_open'],
    'manager',
    'Food Safety Act 1990',
    true,
    true,
    true,
    array['photo', 'text_note'],
    'Confirm all refrigeration units are in range and ready for service.'
  ),
  (
    null,
    'Daily Closing Hygiene Walk',
    'daily_closing_hygiene',
    'End-of-day hygiene walk to verify cleaning, waste removal and closures.',
    'cleaning',
    'health_safety',
    'daily',
    array['after_service'],
    'manager',
    'HACCP',
    false,
    true,
    true,
    array['photo', 'text_note'],
    'Walk through the site to confirm that closing cleaning and shutdown checks are complete.'
  ),
  (
    null,
    'Weekly Hot Holding Validation',
    'weekly_hot_holding_validation',
    'Weekly validation of hot-holding units and monitoring logs.',
    'food_safety',
    'food_safety',
    'weekly',
    array['during_service'],
    'manager',
    'Food Hygiene Regulations',
    true,
    true,
    true,
    array['temperature', 'photo'],
    'Use a calibrated probe to validate hot holding temperatures remain above 63°C.'
  ),
  (
    null,
    'Weekly Refrigeration Audit',
    'weekly_refrigeration_audit',
    'Deep-dive review of refrigeration performance, stock rotation and maintenance.',
    'food_safety',
    'food_safety',
    'weekly',
    array['before_open'],
    'manager',
    'CookSafe',
    true,
    true,
    true,
    array['temperature', 'text_note'],
    'Check recorded temperatures, rotate stock and inspect door seals, gaskets and cleanliness.'
  ),
  (
    null,
    'Monthly Cleaning Verification',
    'monthly_cleaning_verification',
    'Monthly verification of detailed cleaning schedules and chemical controls.',
    'cleaning',
    'health_safety',
    'monthly',
    array['after_service'],
    'manager',
    'HACCP',
    false,
    true,
    true,
    array['photo', 'text_note'],
    'Verify deep cleaning tasks, review chemical storage and confirm documentation is complete.'
  ),
  (
    null,
    'Fire Safety Drill & Equipment Check',
    'fire_safety_drill_equipment',
    'Checklist for monthly fire drill and inspection of fire safety equipment.',
    'fire',
    'health_safety',
    'monthly',
    array['morning'],
    'manager',
    'Regulatory Reform (Fire Safety) Order 2005',
    true,
    true,
    true,
    array['photo', 'text_note'],
    'Conduct a fire drill, test alarms and record extinguisher, emergency lighting and exit checks.'
  ),
  (
    null,
    'Emergency Lighting & Escape Route Check',
    'emergency_lighting_escape_route',
    'Weekly emergency lighting flick test and escape route inspection.',
    'fire',
    'health_safety',
    'weekly',
    array['morning'],
    'manager',
    'BS 5266',
    false,
    true,
    true,
    array['photo', 'text_note'],
    'Perform a flick test and confirm escape routes, signage and exits remain clear.'
  ),
  (
    null,
    'First Aid & PPE Station Check',
    'first_aid_ppe_station_check',
    'Weekly verification of first aid supplies, PPE availability and expiry dates.',
    'health_safety',
    'health_safety',
    'weekly',
    array['morning'],
    'manager',
    'Health & Safety at Work Act 1974',
    false,
    true,
    true,
    array['photo', 'text_note'],
    'Inspect first aid kits, eyewash bottles, PPE stations and replenish low stock items.'
  ),
  (
    null,
    'Pest Control Walk & Bait Review',
    'pest_control_walk_bait',
    'Weekly pest control monitoring including bait station checks.',
    'health_safety',
    'health_safety',
    'weekly',
    array['during_service'],
    'manager',
    'Food Safety (General Food Hygiene) Regulations',
    true,
    true,
    true,
    array['photo', 'text_note'],
    'Walk the site for signs of pest activity and confirm bait stations are intact and recorded.'
  ),
  (
    null,
    'Waste Management & Recycling Audit',
    'waste_management_recycling_audit',
    'Monthly review of waste handling, segregation and contractor paperwork.',
    'compliance',
    'compliance',
    'monthly',
    array['morning'],
    'manager',
    'Environmental Protection Act 1990',
    false,
    true,
    true,
    array['photo', 'text_note'],
    'Audit waste segregation, storage areas and confirm uplifts / transfer notes are on file.'
  )
on conflict (coalesce(company_id, '00000000-0000-0000-0000-000000000000'::uuid), slug) do nothing;
