import { View, Text } from '@react-pdf/renderer';
import { baseStyles } from './PDFStyles';

interface PDFFooterProps {
  generatedText?: string;
}

export function PDFFooter({ generatedText = 'Generated by Opsly' }: PDFFooterProps) {
  return (
    <View style={baseStyles.footer} fixed>
      <Text>{generatedText}</Text>
      <Text
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}
