-- ============================================
-- FIX CRON TASK SOURCE IDENTIFICATION
-- Mark cron-generated tasks so they don't appear in Active Tasks page
-- Active Tasks should only show manually created tasks from templates
-- ============================================

-- Update the cron function to mark tasks as generated by cron
CREATE OR REPLACE FUNCTION generate_daily_tasks_direct()
RETURNS TABLE(
  daily_created bigint,
  weekly_created bigint,
  monthly_created bigint,
  errors text[]
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_daily_count bigint := 0;
  v_weekly_count bigint := 0;
  v_monthly_count bigint := 0;
  v_errors text[] := '{}';
  v_today date;
  v_day_of_week int;
  v_date_of_month int;
  v_template record;
  v_site record;
  v_dayparts text[];
  v_daypart text;
  v_existing_dayparts text[];
BEGIN
  v_today := CURRENT_DATE;
  v_day_of_week := EXTRACT(DOW FROM v_today); -- 0=Sunday, 1=Monday, etc.
  v_date_of_month := EXTRACT(DAY FROM v_today);
  
  -- ===== DAILY TASKS =====
  FOR v_template IN 
    SELECT * FROM task_templates 
    WHERE frequency = 'daily' 
      AND is_active = true
  LOOP
    BEGIN
      -- Get dayparts
      v_dayparts := v_template.dayparts;
      IF v_dayparts IS NULL OR array_length(v_dayparts, 1) IS NULL THEN
        v_dayparts := ARRAY['anytime'];
      END IF;
      
      -- Get all active sites
      FOR v_site IN 
        SELECT id, company_id FROM sites 
        WHERE (status IS NULL OR status != 'inactive')
          AND (v_template.site_id IS NULL OR id = v_template.site_id)
          AND (v_template.company_id IS NULL OR company_id = v_template.company_id)
      LOOP
        DECLARE
          v_existing_combinations TEXT[];
          v_daypart_times JSONB;
          v_times_for_daypart TEXT[];
          v_daypart_time_value JSONB;
          v_time_str TEXT;
        BEGIN
          -- Get daypart_times from recurrence_pattern
          IF v_template.recurrence_pattern ? 'daypart_times' THEN
            v_daypart_times := v_template.recurrence_pattern->'daypart_times';
          END IF;
          
          -- Check existing tasks for this template/site/date
          SELECT array_agg(DISTINCT COALESCE(daypart, '') || '|' || COALESCE(due_time::text, '')) 
          INTO v_existing_combinations
          FROM checklist_tasks
          WHERE template_id = v_template.id
            AND site_id = v_site.id
            AND due_date = v_today;
          
          -- Create tasks for each daypart with its specific times
          FOREACH v_daypart IN ARRAY v_dayparts
          LOOP
            -- Get times for this specific daypart
            IF v_daypart_times IS NOT NULL AND v_daypart_times ? v_daypart THEN
              v_daypart_time_value := v_daypart_times->v_daypart;
              
              -- Handle different formats: string (single or comma-separated) or array
              IF jsonb_typeof(v_daypart_time_value) = 'array' THEN
                SELECT array_agg(value::text) INTO v_times_for_daypart
                FROM jsonb_array_elements_text(v_daypart_time_value);
              ELSIF jsonb_typeof(v_daypart_time_value) = 'string' THEN
                v_time_str := trim(both '"' from v_daypart_time_value::text);
                IF v_time_str LIKE '%,%' THEN
                  v_times_for_daypart := string_to_array(v_time_str, ',');
                  SELECT array_agg(trim(both ' ' from unnest)) INTO v_times_for_daypart
                  FROM unnest(v_times_for_daypart);
                ELSE
                  v_times_for_daypart := ARRAY[v_time_str];
                END IF;
              END IF;
            END IF;
            
            -- If no daypart-specific times, fall back to time_of_day or default
            IF v_times_for_daypart IS NULL OR array_length(v_times_for_daypart, 1) IS NULL THEN
              IF v_template.time_of_day IS NOT NULL THEN
                v_times_for_daypart := ARRAY[v_template.time_of_day];
              ELSE
                v_times_for_daypart := ARRAY['09:00']; -- Default
              END IF;
            END IF;
            
            -- Create one task for each time for this daypart
            FOREACH v_time_str IN ARRAY v_times_for_daypart
            LOOP
              DECLARE
                v_combination TEXT := COALESCE(v_daypart, '') || '|' || COALESCE(v_time_str, '');
              BEGIN
                -- Check if this combination already exists
                IF v_existing_combinations IS NULL OR NOT (v_combination = ANY(v_existing_combinations)) THEN
                  INSERT INTO checklist_tasks (
                    template_id,
                    company_id,
                    site_id,
                    due_date,
                    due_time,
                    daypart,
                    assigned_to_role,
                    assigned_to_user_id,
                    status,
                    priority,
                    generated_at,
                    expires_at,
                    task_data
                  ) VALUES (
                    v_template.id,
                    v_site.company_id,
                    v_site.id,
                    v_today,
                    v_time_str::TIME,
                    v_daypart,
                    v_template.assigned_to_role,
                    v_template.assigned_to_user_id,
                    'pending',
                    CASE WHEN v_template.is_critical THEN 'critical' ELSE 'medium' END,
                    NOW(),
                    v_today + INTERVAL '1 day',
                    jsonb_build_object(
                      'source', 'cron', -- MARK AS CRON-GENERATED
                      'dayparts', v_dayparts,
                      'daypart_times', v_daypart_times,
                      'daypart', v_daypart,
                      'time', v_time_str,
                      'checklistItems', COALESCE((v_template.recurrence_pattern->'default_checklist_items')::jsonb, '[]'::jsonb)
                    )
                  );
                  v_daily_count := v_daily_count + 1;
                END IF;
              END;
            END LOOP;
          END LOOP;
        END;
      END LOOP;
    EXCEPTION WHEN OTHERS THEN
      v_errors := array_append(v_errors, 'Daily template ' || v_template.id || ': ' || SQLERRM);
    END;
  END LOOP;
  
  -- ===== WEEKLY TASKS =====
  FOR v_template IN 
    SELECT * FROM task_templates 
    WHERE frequency = 'weekly' 
      AND is_active = true
  LOOP
    BEGIN
      DECLARE
        v_pattern jsonb := v_template.recurrence_pattern;
        v_target_days int[];
      BEGIN
        IF v_pattern ? 'days' THEN
          v_target_days := ARRAY(SELECT jsonb_array_elements_text(v_pattern->'days')::int);
        ELSE
          v_target_days := ARRAY[1]; -- Default to Monday
        END IF;
        
        IF NOT (v_day_of_week = ANY(v_target_days)) THEN
          CONTINUE;
        END IF;
        
        v_dayparts := v_template.dayparts;
        IF v_dayparts IS NULL OR array_length(v_dayparts, 1) IS NULL THEN
          v_dayparts := ARRAY['anytime'];
        END IF;
        
        FOR v_site IN 
          SELECT id, company_id FROM sites 
          WHERE (status IS NULL OR status != 'inactive')
            AND (v_template.site_id IS NULL OR id = v_template.site_id)
            AND (v_template.company_id IS NULL OR company_id = v_template.company_id)
        LOOP
          DECLARE
            v_existing_combinations TEXT[];
            v_daypart_times JSONB;
            v_times_for_daypart TEXT[];
            v_daypart_time_value JSONB;
            v_time_str TEXT;
          BEGIN
            IF v_pattern ? 'daypart_times' THEN
              v_daypart_times := v_pattern->'daypart_times';
            END IF;
            
            SELECT array_agg(DISTINCT COALESCE(daypart, '') || '|' || COALESCE(due_time::text, '')) 
            INTO v_existing_combinations
            FROM checklist_tasks
            WHERE template_id = v_template.id
              AND site_id = v_site.id
              AND due_date = v_today;
            
            FOREACH v_daypart IN ARRAY v_dayparts
            LOOP
              v_times_for_daypart := NULL;
              IF v_daypart_times IS NOT NULL AND v_daypart_times ? v_daypart THEN
                v_daypart_time_value := v_daypart_times->v_daypart;
                
                IF jsonb_typeof(v_daypart_time_value) = 'array' THEN
                  SELECT array_agg(value::text) INTO v_times_for_daypart
                  FROM jsonb_array_elements_text(v_daypart_time_value);
                ELSIF jsonb_typeof(v_daypart_time_value) = 'string' THEN
                  v_time_str := trim(both '"' from v_daypart_time_value::text);
                  IF v_time_str LIKE '%,%' THEN
                    v_times_for_daypart := string_to_array(v_time_str, ',');
                    SELECT array_agg(trim(both ' ' from unnest)) INTO v_times_for_daypart
                    FROM unnest(v_times_for_daypart);
                  ELSE
                    v_times_for_daypart := ARRAY[v_time_str];
                  END IF;
                END IF;
              END IF;
              
              IF v_times_for_daypart IS NULL OR array_length(v_times_for_daypart, 1) IS NULL THEN
                IF v_template.time_of_day IS NOT NULL THEN
                  v_times_for_daypart := ARRAY[v_template.time_of_day];
                ELSE
                  v_times_for_daypart := ARRAY['09:00'];
                END IF;
              END IF;
              
              FOREACH v_time_str IN ARRAY v_times_for_daypart
              LOOP
                DECLARE
                  v_combination TEXT := COALESCE(v_daypart, '') || '|' || COALESCE(v_time_str, '');
                BEGIN
                  IF v_existing_combinations IS NULL OR NOT (v_combination = ANY(v_existing_combinations)) THEN
                    INSERT INTO checklist_tasks (
                      template_id,
                      company_id,
                      site_id,
                      due_date,
                      due_time,
                      daypart,
                      assigned_to_role,
                      assigned_to_user_id,
                      status,
                      priority,
                      generated_at,
                      expires_at,
                      task_data
                    ) VALUES (
                      v_template.id,
                      v_site.company_id,
                      v_site.id,
                      v_today,
                      v_time_str::TIME,
                      v_daypart,
                      v_template.assigned_to_role,
                      v_template.assigned_to_user_id,
                      'pending',
                      CASE WHEN v_template.is_critical THEN 'critical' ELSE 'medium' END,
                      NOW(),
                      v_today + INTERVAL '1 day',
                      jsonb_build_object(
                        'source', 'cron', -- MARK AS CRON-GENERATED
                        'dayparts', v_dayparts,
                        'daypart_times', v_daypart_times,
                        'daypart', v_daypart,
                        'time', v_time_str,
                        'checklistItems', COALESCE((v_template.recurrence_pattern->'default_checklist_items')::jsonb, '[]'::jsonb)
                      )
                    );
                    v_weekly_count := v_weekly_count + 1;
                  END IF;
                END;
              END LOOP;
            END LOOP;
          END;
        END LOOP;
      END;
    EXCEPTION WHEN OTHERS THEN
      v_errors := array_append(v_errors, 'Weekly template ' || v_template.id || ': ' || SQLERRM);
    END;
  END LOOP;
  
  -- ===== MONTHLY TASKS =====
  FOR v_template IN 
    SELECT * FROM task_templates 
    WHERE frequency = 'monthly' 
      AND is_active = true
  LOOP
    BEGIN
      DECLARE
        v_pattern jsonb := v_template.recurrence_pattern;
        v_target_dates int[];
      BEGIN
        IF v_pattern ? 'dates' THEN
          v_target_dates := ARRAY(SELECT jsonb_array_elements_text(v_pattern->'dates')::int);
        ELSE
          v_target_dates := ARRAY[1]; -- Default to 1st of month
        END IF;
        
        IF NOT (v_date_of_month = ANY(v_target_dates)) THEN
          CONTINUE;
        END IF;
        
        v_dayparts := v_template.dayparts;
        IF v_dayparts IS NULL OR array_length(v_dayparts, 1) IS NULL THEN
          v_dayparts := ARRAY['anytime'];
        END IF;
        
        FOR v_site IN 
          SELECT id, company_id FROM sites 
          WHERE (status IS NULL OR status != 'inactive')
            AND (v_template.site_id IS NULL OR id = v_template.site_id)
            AND (v_template.company_id IS NULL OR company_id = v_template.company_id)
        LOOP
          DECLARE
            v_existing_combinations TEXT[];
            v_daypart_times JSONB;
            v_times_for_daypart TEXT[];
            v_daypart_time_value JSONB;
            v_time_str TEXT;
          BEGIN
            IF v_pattern ? 'daypart_times' THEN
              v_daypart_times := v_pattern->'daypart_times';
            END IF;
            
            SELECT array_agg(DISTINCT COALESCE(daypart, '') || '|' || COALESCE(due_time::text, '')) 
            INTO v_existing_combinations
            FROM checklist_tasks
            WHERE template_id = v_template.id
              AND site_id = v_site.id
              AND due_date = v_today;
            
            FOREACH v_daypart IN ARRAY v_dayparts
            LOOP
              v_times_for_daypart := NULL;
              IF v_daypart_times IS NOT NULL AND v_daypart_times ? v_daypart THEN
                v_daypart_time_value := v_daypart_times->v_daypart;
                
                IF jsonb_typeof(v_daypart_time_value) = 'array' THEN
                  SELECT array_agg(value::text) INTO v_times_for_daypart
                  FROM jsonb_array_elements_text(v_daypart_time_value);
                ELSIF jsonb_typeof(v_daypart_time_value) = 'string' THEN
                  v_time_str := trim(both '"' from v_daypart_time_value::text);
                  IF v_time_str LIKE '%,%' THEN
                    v_times_for_daypart := string_to_array(v_time_str, ',');
                    SELECT array_agg(trim(both ' ' from unnest)) INTO v_times_for_daypart
                    FROM unnest(v_times_for_daypart);
                  ELSE
                    v_times_for_daypart := ARRAY[v_time_str];
                  END IF;
                END IF;
              END IF;
              
              IF v_times_for_daypart IS NULL OR array_length(v_times_for_daypart, 1) IS NULL THEN
                IF v_template.time_of_day IS NOT NULL THEN
                  v_times_for_daypart := ARRAY[v_template.time_of_day];
                ELSE
                  v_times_for_daypart := ARRAY['09:00'];
                END IF;
              END IF;
              
              FOREACH v_time_str IN ARRAY v_times_for_daypart
              LOOP
                DECLARE
                  v_combination TEXT := COALESCE(v_daypart, '') || '|' || COALESCE(v_time_str, '');
                BEGIN
                  IF v_existing_combinations IS NULL OR NOT (v_combination = ANY(v_existing_combinations)) THEN
                    INSERT INTO checklist_tasks (
                      template_id,
                      company_id,
                      site_id,
                      due_date,
                      due_time,
                      daypart,
                      assigned_to_role,
                      assigned_to_user_id,
                      status,
                      priority,
                      generated_at,
                      expires_at,
                      task_data
                    ) VALUES (
                      v_template.id,
                      v_site.company_id,
                      v_site.id,
                      v_today,
                      v_time_str::TIME,
                      v_daypart,
                      v_template.assigned_to_role,
                      v_template.assigned_to_user_id,
                      'pending',
                      CASE WHEN v_template.is_critical THEN 'critical' ELSE 'medium' END,
                      NOW(),
                      v_today + INTERVAL '1 day',
                      jsonb_build_object(
                        'source', 'cron', -- MARK AS CRON-GENERATED
                        'dayparts', v_dayparts,
                        'daypart_times', v_daypart_times,
                        'daypart', v_daypart,
                        'time', v_time_str,
                        'checklistItems', COALESCE((v_template.recurrence_pattern->'default_checklist_items')::jsonb, '[]'::jsonb)
                      )
                    );
                    v_monthly_count := v_monthly_count + 1;
                  END IF;
                END;
              END LOOP;
            END LOOP;
          END;
        END LOOP;
      END;
    EXCEPTION WHEN OTHERS THEN
      v_errors := array_append(v_errors, 'Monthly template ' || v_template.id || ': ' || SQLERRM);
    END;
  END LOOP;
  
  RETURN QUERY SELECT v_daily_count, v_weekly_count, v_monthly_count, v_errors;
END;
$$;

COMMENT ON FUNCTION generate_daily_tasks_direct() IS 
'Automatically generates daily, weekly, and monthly tasks for all active templates and sites.
Runs via pg_cron every day at 3:00 AM UTC. Tasks are marked with source=''cron'' in task_data
so they can be filtered out from Active Tasks page (which should only show manually created tasks).';


