'use client';

// Re-export commonly used Phosphor icons for easy migration from lucide-react
// Maps old Lucide names → Phosphor equivalents
//
// Usage: import { Home, Search, Bell } from '@/components/ui/icons';
// For OpslyIcon wrapper: import { OpslyIcon } from '@/components/ui/OpslyIcon';

export {
  // --- Navigation ---
  House as Home,
  House as HomeIcon,
  MagnifyingGlass as Search,
  Gear as Settings,
  GearSix as Settings2,
  List as Menu,
  Sidebar as PanelLeft,
  Sidebar as PanelRight,
  SidebarSimple as PanelLeftClose,
  ArrowSquareOut as ExternalLink,
  SignOut as LogOut,
  SignIn as LogIn,

  // --- Users ---
  User,
  Users as Users2,
  UsersThree as Users,
  UserCircle,
  UserCircle as UserCircle2,
  UserPlus,
  UserMinus,
  UserMinus as UserX,
  UserGear as UserCog,
  UserCheck,
  UsersThree as UsersRound,

  // --- Notifications ---
  Bell,
  Bell as BellIcon,
  BellRinging as BellRing,
  BellSlash as BellOff,
  Notification as BellDot,

  // --- Charts ---
  ChartBar as BarChart,
  ChartBar as BarChart2,
  ChartBar as BarChart3,
  ChartLine as LineChart,
  ChartPie as PieChart,
  ChartDonut as DonutChart,
  TrendUp,
  TrendUp as TrendingUp,
  TrendDown,
  TrendDown as TrendingDown,
  Presentation as BarChartHorizontal,
  Pulse as Activity,
  Gauge,

  // --- Calendar / Time ---
  Calendar,
  CalendarCheck,
  CalendarBlank as CalendarDays,
  CalendarPlus,
  Clock,
  Timer,
  Alarm as AlarmClock,
  ClockCounterClockwise as History,
  Repeat,

  // --- Communication ---
  Envelope as Mail,
  EnvelopeSimple as MailOpen,
  ChatCircle as MessageCircle,
  ChatText as MessageSquare,
  ChatCircle as MessageSquareWarning,
  ChatDots as MessageCircleDots,
  PaperPlaneTilt as Send,
  Megaphone,
  Phone,
  At,
  Microphone as Mic,
  MicrophoneSlash as MicOff,

  // --- Status / Alerts ---
  CheckCircle,
  CheckCircle as CheckCircle2,
  Warning as AlertTriangle,
  WarningCircle as AlertCircle,
  WarningOctagon as OctagonAlert,
  Siren as AlertOctagon,
  WarningDiamond as ShieldAlert,
  Info,
  Question as HelpCircle,
  Question as CircleHelp,
  Prohibit as Ban,
  Prohibit as CircleOff,

  // --- Actions ---
  Plus,
  PlusCircle,
  Minus,
  MinusCircle,
  X,
  XCircle,
  Check,
  CheckSquare,
  Copy,
  Trash,
  Trash as Trash2,
  PencilSimple as Pencil,
  PencilSimple as Edit,
  PencilSimple as Edit2,
  PencilSimple as Edit3,
  Eraser,
  FloppyDisk as Save,
  Download,
  Download as DownloadSimple,
  Upload,
  Upload as UploadSimple,
  UploadSimple as UploadCloud,
  FunnelSimple as Filter,
  FunnelSimple as SlidersHorizontal,
  Funnel,
  Printer,
  Share,
  ArrowBendUpLeft as Reply,
  ArrowBendUpRight as Forward,

  // --- Arrows / Chevrons ---
  CaretDown as ChevronDown,
  CaretUp as ChevronUp,
  CaretRight as ChevronRight,
  CaretLeft as ChevronLeft,
  CaretDoubleRight as ChevronsRight,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleUp as ChevronsUp,
  CaretDoubleDown as ChevronsDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowsClockwise as RefreshCw,
  ArrowsClockwise as RefreshCcw,
  ArrowCounterClockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  ArrowsLeftRight,
  ArrowsLeftRight as ArrowLeftRight,
  ArrowsLeftRight as ArrowRightLeft,
  ArrowsDownUp,
  ArrowsOut as Maximize2,
  ArrowsIn as Minimize2,
  ArrowDown as MoveDown,
  ArrowUp as MoveUp,
  Swap,

  // --- Media ---
  Play,
  Pause,
  PauseCircle,
  Stop,
  SkipForward,
  SkipBack,
  FastForward,
  Rewind,
  Microphone,
  SpeakerHigh as Volume2,
  SpeakerX as VolumeX,
  VideoCamera as Video,
  FilmStrip as Film,
  Camera,
  Image as ImageIcon,
  Aperture,
  Crop,

  // --- Files / Documents ---
  FileText,
  File,
  FilePlus,
  FilePlus as FilePlus2,
  FileMagnifyingGlass as FileCheck,
  FileX as FileX,
  FileCsv as FileSpreadsheet,
  FileImage as FileImage,
  FileJs as FileJson,
  Archive as FileBox,
  NotePencil as FileEdit,
  Clipboard,
  ClipboardText as ClipboardList,
  ClipboardText as ClipboardCheck,
  BookOpen,
  Books,
  Notebook,
  Note,
  Notepad,

  // --- Layout ---
  Table,
  Table as Table2,
  Rows,
  Columns,
  Columns as Columns2,
  Columns as Columns3,
  GridFour as LayoutGrid,
  GridFour as Grid,
  SquaresFour as Grid3x3,
  SquaresFour as LayoutDashboard,
  Layout as LayoutTemplate,
  Kanban,

  // --- Security ---
  Lock,
  LockOpen as Unlock,
  ShieldCheck,
  Shield,
  Key,
  Key as KeyRound,
  Fingerprint,
  Eye,
  EyeSlash as EyeOff,

  // --- Business ---
  Briefcase,
  Buildings as Building2,
  Building as Building,
  Factory,
  Handshake,
  Receipt,
  Barcode,
  ShoppingCart,
  Bag as ShoppingBag,
  Money as DollarSign,
  CurrencyGbp as PoundSign,
  CurrencyGbp as PoundSterling,
  CreditCard,
  Bank,
  Wallet,
  HandCoins as Coins,
  CurrencyDollar as Currency,
  Scales as Scale,
  Coin,

  // --- Shapes ---
  Circle,
  Square,
  Triangle,
  Diamond,
  Hexagon,
  Polygon,
  Cube,
  Cube as Box,
  Package,
  Package as Boxes,
  Cylinder,
  Shapes,
  Stack as Layers,

  // --- Development ---
  GitBranch,
  GitCommit,
  GitDiff as GitCompare,
  Terminal,
  Code,
  Plugs as Plug,
  WifiHigh as Wifi,
  WifiSlash as WifiOff,
  Bluetooth,
  Database,
  HardDrive,
  Cpu,
  Circuitry as CircuitBoard,
  Robot,
  DeviceMobile as Smartphone,
  DeviceMobile as Vibrate,
  Desktop as Monitor,

  // --- Tools ---
  Wrench,
  Wrench as WrenchIcon,
  Hammer,
  Screwdriver,
  Nut,
  GearFine as Cog,
  Toolbox,
  Scissors,
  PaintBucket,
  PaintBrush as Paintbrush,
  Palette,
  Lightbulb,
  Rocket,

  // --- Food / Hospitality ---
  ForkKnife,
  ForkKnife as Utensils,
  ForkKnife as UtensilsCrossed,
  CookingPot,
  CookingPot as ChefHat,
  Coffee,
  BeerBottle as Beer,
  Wine,
  Hamburger,
  Drop as GlassWater,
  Flask as FlaskConical,
  IceCream,

  // --- Nature / Weather ---
  Sun,
  Moon,
  Cloud,
  CloudSun,
  CloudLightning,
  CloudRain,
  CloudSlash as CloudOff,
  CloudSnow,
  Snowflake,
  Wind,
  Drop as Droplet,
  Drop as Droplets,
  ThermometerSimple as Thermometer,
  ThermometerHot as ThermometerSun,
  Umbrella,
  Leaf,
  Tree,
  Flower,
  Mountains,
  Waves,
  Fire,
  Fire as Flame,
  Campfire,

  // --- People / Gestures ---
  HandPointing as Hand,
  ThumbsUp,
  ThumbsDown,
  HandWaving,
  Smiley as Smile,
  MaskHappy as Smile2,
  SmileyMeh as Meh,
  SmileySad as Frown,
  SmileyAngry,
  SmileyWink,

  // --- Health ---
  Heartbeat as HeartPulse,
  Pulse,
  Syringe,
  FirstAid,
  Pill,
  Stethoscope,
  Wheelchair,
  Wheelchair as Accessibility,

  // --- Misc ---
  Lightning as Zap,
  Star,
  Heart,
  Tag,
  MapPin,
  Globe,
  Link,
  Link as Link2,
  LinkBreak as Unlink,
  Paperclip,
  Folder,
  FolderOpen,
  TreeStructure as FolderTree,
  Hash,
  Percent,
  Power,
  QrCode,
  MapTrifold as Map,
  Compass,
  NavigationArrow as Navigation,
  Path,
  Flag,
  Crosshair as Target,
  Crosshair,
  PushPin as Pin,
  Lifebuoy as LifeBuoy,
  Trophy,
  Trophy as Award,
  Medal,
  Crown,
  Certificate,
  GraduationCap,
  Student,
  Chalkboard,
  Exam,
  Quotes as Quote,
  Recycle,
  Archive,
  Archive as Archive2,
  Tray as Inbox,
  Bookmarks as Bookmark,
  Bookmarks as BookmarkCheck,
  DotsSixVertical as GripVertical,
  HardHat as Construction,
  CircleHalf as Contrast,
  Calculator,
  Gavel,
  IdentificationCard as IdCard,
  IdentificationCard as BadgeCheck,

  // --- Spinners / Loading ---
  CircleNotch as Loader2,
  CircleNotch as Loader,
  SpinnerGap as LoaderCircle,
  Spinner,

  // --- Sorting ---
  SortAscending,
  SortDescending,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
  DotsThreeVertical as MoreVertical,
  DotsThree as MoreHorizontal,

  // --- Misc UI ---
  TextT as Type,
  TextAlignLeft as AlignLeft,
  TextAlignCenter as AlignCenter,
  TextAlignRight as AlignRight,
  TextAa as CaseSensitive,
  Sliders as Settings2Alt,
  Empty as CircleDashed,
  CheckFat as BadgeCheckFill,
  SignOut as DoorOpen,
  DoorOpen as Door,
  Sparkle,
  Sparkle as Sparkles,
  Asterisk,
  Atom,
  Virus,
  Bug,
  BugBeetle as BugIcon,
  Butterfly,
  PawPrint,
  Horse,
  Cat,
  Dog,
  FishSimple as Fish,
  Bird,
  Sunglasses,
  TShirt as Shirt,
  Sneaker as Footprints,
  Backpack,
  SuitcaseSimple as Luggage,
  Ticket,
  Gift,
  Balloon,
  Confetti as PartyPopper,
  Cake,
  Bed,
  ListChecks,
  ListBullets,

  // --- Additional mappings (Lucide names used in codebase) ---
  ArrowDownRight,
  ArrowsDownUp as ArrowUpDown,
  Money as Banknote,
  Flask as Beaker,
  TextB as Bold,
  Robot as Bot,
  Brain,
  CalendarSlash as CalendarOff,
  ClipboardText as ClipboardX,
  Cookie,
  FileCode,
  GridFour as Grid3X3,
  DotsSix as Grip,
  TextHOne as Heading1,
  TextHTwo as Heading2,
  Headphones,
  Image,
  TextItalic as Italic,
  ListDashes as LayoutList,
  List,
  ListNumbers as ListOrdered,
  TreeStructure as Network,
  Notebook as NotebookText,
  Package as PackageCheck,
  PencilLine as PenLine,
  PhoneCall,
  ShareNetwork as Share2,
  Storefront as Store,
  SunHorizon as Sunrise,
  SunDim as Sunset,
  Tag as Tags,
  Truck,
  MagicWand as Wand2,
  Warehouse,
  FlowArrow as Workflow,
} from '@phosphor-icons/react';

// Type export for components that import LucideIcon type
export type { IconProps as LucideIcon } from '@phosphor-icons/react';
